import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-green-500 flex justify-center items-center h-screen">
        Walker Paradise
      </main>

      <footer className="">Jade</footer>
    </div>
  );
};

export default Home;
